[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["CI=false DISABLE_ESLINT_PLUGIN=true npm run build"]

[phases.start]
cmd = "npx serve -s build -l $PORT"

[metadata]
watch = ["package.json", "src/**", "public/**"]